name: RustDesk Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      # Step 1: Download & Install RustDesk
      - name: Download & Install RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe" -OutFile "rustdesk.exe"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=0" -OutFile "time.py"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/vji7ekyslpbovokpqeay3/loop.bat?rlkey=876nfzm3qdmyqhc1jckgqjcld&dl=0" -OutFile "loop.bat"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/cwbwdo2n3tt8rbqmugc6h/show.bat?rlkey=41m0ds12mg6e28giib3zqlf6w&dl=0" -OutFile "show.bat"
          
          pip install pyautogui --quiet
          pip install psutil --quiet

      # Step 2: Jalankan RustDesk
      - name: Jalankan RustDesk
        run: cmd /c start "" rustdesk.exe

      # Step 3: Jalankan Script Login (untuk ambil ID RustDesk)
      - name: Jalankan Login Otomatis
        run: |
          cmd /c show.bat
          # Menyimpan ID RustDesk ke file id.txt
          echo "RustDesk ID: $(Get-Content "C:\Users\Public\RustDeskID.txt")" > id.txt

      # Step 4: Keep Alive VPS supaya tetap hidup
      - name: Keep Alive
        run: powershell -Command "while ($true) { Start-Sleep -Seconds 60 }"

      # Step 5: Upload ID ke Artifact
      - name: Upload RustDesk ID
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-id
          path: id.txt
