name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download dan Install Essentials
        run: |
          curl -L -o Downloads.bat "https://raw.githubusercontent.com/elfarid09/Stb-dev/refs/heads/main/al/Downloads.bat"
          cmd /c Downloads.bat

      - name: Jalankan RustDesk + Login Script
        run: cmd /c show.bat

      - name: Tampilkan ID dan Password RustDesk
        shell: powershell
        run: |
          Start-Sleep -Seconds 5
          if (Test-Path "C:\Users\Public\RustDeskID.txt") {
            $id = Get-Content "C:\Users\Public\RustDeskID.txt"
            Write-Host "RustDesk ID: $id"
          } else {
            Write-Host "RustDesk ID: Tidak ditemukan"
          }
