name: Windows with RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: RustDesk RDP
    runs-on: windows-latest
    timeout-minutes: 360  # Maksimal durasi 6 jam (bisa kamu ubah)

    steps:
      - name: Download RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.exe" -OutFile "rustdesk.exe"

      - name: Jalankan RustDesk
        run: |
          Start-Process -FilePath "rustdesk.exe"
          Write-Output "Tunggu 1-2 menit, lalu cek ID & Password RustDesk dari client kamu."

      - name: Jaga sesi tetap hidup
        run: |
          for ($i=0; $i -lt 3600; $i++) {
            Start-Sleep -Seconds 60
          }
