name: RustDesk Windows

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Jalankan Script Otomatis
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/elfarid09/Stb-dev/refs/heads/main/al/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
