name: RustDesk Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      # Step 1: Download & Install RustDesk
      - name: Download & Install RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe" -OutFile "rustdesk.exe"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=0" -OutFile "time.py"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/vji7ekyslpbovokpqeay3/loop.bat?rlkey=876nfzm3qdmyqhc1jckgqjcld&dl=0" -OutFile "loop.bat"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/cwbwdo2n3tt8rbqmugc6h/show.bat?rlkey=41m0ds12mg6e28giib3zqlf6w&dl=0" -OutFile "show.bat"
          
          pip install pyautogui --quiet
          pip install psutil --quiet

      # Step 2: Jalankan RustDesk
      - name: Jalankan RustDesk
        run: cmd /c start "" rustdesk.exe

      # Step 3: Tunggu ID muncul dan ambil ID RustDesk
      - name: Tunggu dan Ambil ID RustDesk
        run: |
          # Tunggu beberapa detik lebih lama agar RustDesk menulis ID ke file
          Start-Sleep -Seconds 15
          
          # Cek apakah file RustDeskID.txt ada
          if (Test-Path "C:\Users\Public\RustDeskID.txt") {
            $rustdeskID = Get-Content "C:\Users\Public\RustDeskID.txt"
            Write-Host "RustDesk ID: $rustdeskID"
          } else {
            Write-Host "ID RustDesk tidak ditemukan."
          }

      # Step 4: Keep Alive
      - name: Keep Alive
        run: powershell -Command "while ($true) { Start-Sleep -Seconds 60 }"
